### ISSUE TITLE
How can I add color bar to heatmap?

### ISSUE THREAD

**Issue by arihelrnan** [arihelrnan/Endophyte_microbiome_Vanilla_planifolia#7]
I use heatmaps to show distances between samples similar to what is shown in NMDS. 

I use my distance matrices as inputs for a `gplots` library, and with `heatmap.2` command I make heatmap plot with data in distance matrix. This command automatically groups samples by similarity using a dendrogram in plot. This is my arguments syntax:
```
distancia_organo=as.matrix(bray_ps.bxn) #Convert distance object to matrix object
heatmap.2(distancia_organo, key=T, trace="none") #Make heatmap with dendogram   
```
 This is result 
![image](https://user-images.githubusercontent.com/71803692/101430194-20d03f80-38ca-11eb-8a65-d523d4fe2f02.png)

I think it's easier to understand if I indicates which are the groups of samples that I am comparing. I can make this adding color bar that indicates sample of groups. For example, the plot view like this: 

![image](https://user-images.githubusercontent.com/71803692/101431194-08f9bb00-38cc-11eb-9d3c-b8adf695d21b.png)

In my case, I have two variables (Plant State and Organ), and I want make heatmap with two color bar that indicate this two variables. I have the meta For example this plot: 

![image](https://user-images.githubusercontent.com/71803692/101431712-064b9580-38cd-11eb-889c-bf03016548e3.png)

In R Documentation of `heatmap.2` function (https://www.rdocumentation.org/packages/gplots/versions/3.1.1/topics/heatmap.2), I can find the arguments `ColSideColors` and `RowSideColors` but I am not sure of how works.

**Comment by arihelrnan** [comment]
Metadata file with groups yhis is: 
[Mapping_file](https://github.com/arihelrnan/Endophyte_microbiome_Vanilla_planifolia/blob/master/Meta/mapping_file.txt)

**Comment by arihelrnan** [comment]
This is the distance matrix:
[Distance_matrix](https://github.com/arihelrnan/Endophyte_microbiome_Vanilla_planifolia/blob/master/Meta/bray_ps.bxn)

**Comment by NellyJazminPC** [comment]
This tutorial could help to know how the second figure was constructed

https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package/

**Comment by arihelrnan** [comment]
Load libraries with this command:
```
packages <-c("ape","dplyr","ggplot2","gplots","lme4","miLineage","phangorn","plotly","tidyr","vegan","VennDiagram","metacoder","phyloseq")
lib <- lapply(packages, require, character.only = TRUE)
```

**Comment by arihelrnan** [comment]
I use the `pheatmap` library and I have take a example of this page (https://webcache.googleusercontent.com/search?q=cache:HnpIV6BkK7gJ:https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package/+&cd=2&hl=es-419&ct=clnk&gl=mx). I have the problem with make the plot, and I get this error message: 
```
Error in .Call.graphics(C_palette2, .Call(C_palette2, NULL)) : 
  invalid graphics state
```

**Comment by valeriafloral** [comment]
I found a easier solution using `heatmaply`package. It gives me this graph

![image](https://user-images.githubusercontent.com/59807620/101506036-9673f400-393a-11eb-9c88-9fe3e03116ac.png)

The code I used was:

```
#Download the dataframe
datos <- "https://raw.githubusercontent.com/arihelrnan/Endophyte_microbiome_Vanilla_planifolia/master/Meta/bray_ps.bxn"
distancia_organo <- read.delim(datos, sep= "\t", header= T, row.names = "X")

#Heatmap
library(heatmaply)
heatmaply(distancia_organo, scale = "none", RowSideColors= rainbow(nrow(distancia_organo)), ColSideColors=rainbow(ncol(distancia_organo)))
```

I don't know if this plot is informative

**Comment by solnavss** [comment]
I might found Ariel's error solution: I found this to occur when you mix ggplot charts with plot charts in the same session. Using the 'dev.off' solution solves the issue. You just need to run $ dev.off

**Comment by VeronicaGlez** [comment]
We could result this Issue with this commands:
```
##ARIEL DATA
disA<- read.delim("bray_ps_bxn.txt", sep = "\t", header = T, row.names = "X")
dis=as.matrix(disA)
pheatmap(dis)
map <- read.delim("mapping_file.txt", sep = "\t", header= T, row.names = "X")
pheatmap(dis, annotation_row = map, annotation_col = map)
```
The files has a little problem with the row names, because they does not have a common column between them, we change manually and work.
![Ariel_plot](https://user-images.githubusercontent.com/17887504/101508374-33379100-393d-11eb-8952-693dbbcbf1e4.png)

Yeeeei!!! XD

**Comment by arihelrnan** [comment]
I have the error message when I make my heatmap with `heatmaply` library. This is the error message: 
```
Error in grDevices::col2rgb(x, alpha = TRUE) : 
  invalid color name 'Asymptomatic'
```
